package config

import (
	"strconv"
	"strings"

	uicfg "github.com/HexmosTech/git-lrc/ui"
)

func UpsertQuotedConfigValue(content, key, value string) string {
	lines := strings.Split(content, "\n")
	prefix := key + " = "
	replacement := prefix + strconv.Quote(value)
	replaced := false

	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, prefix) {
			lines[i] = replacement
			replaced = true
			break
		}
	}

	if !replaced {
		if len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) != "" {
			lines = append(lines, "")
		}
		lines = append(lines, replacement)
	}

	return strings.Join(lines, "\n")
}

func ReadQuotedConfigValue(content, key string) (string, bool) {
	lines := strings.Split(content, "\n")
	prefix := key + " ="

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if !strings.HasPrefix(trimmed, prefix) {
			continue
		}

		rawValue := strings.TrimSpace(strings.TrimPrefix(trimmed, prefix))
		if rawValue == "" {
			return "", true
		}

		if unquoted, err := strconv.Unquote(rawValue); err == nil {
			return unquoted, true
		}

		return rawValue, true
	}

	return "", false
}

func StripManagedAIConnectorsSection(content, sectionBegin, sectionEnd string) string {
	start := strings.Index(content, sectionBegin)
	if start == -1 {
		return content
	}

	endRelative := strings.Index(content[start:], sectionEnd)
	if endRelative == -1 {
		return content[:start]
	}

	end := start + endRelative + len(sectionEnd)
	if end < len(content) {
		if content[end] == '\r' {
			end++
		}
		if end < len(content) && content[end] == '\n' {
			end++
		}
	}

	return content[:start] + content[end:]
}

func RenderManagedAIConnectorsSection(connectors []uicfg.ConnectorRemote, sectionBegin, sectionEnd string) string {
	var builder strings.Builder
	builder.WriteString(sectionBegin)
	builder.WriteString("\n")
	builder.WriteString("# Generated by lrc ui. This section is auto-managed and will be replaced.\n")

	for _, connector := range connectors {
		builder.WriteString("\n[[ai_connectors]]\n")
		builder.WriteString("id = ")
		builder.WriteString(strconv.FormatInt(connector.ID, 10))
		builder.WriteString("\n")
		builder.WriteString("provider_name = ")
		builder.WriteString(strconv.Quote(connector.ProviderName))
		builder.WriteString("\n")
		builder.WriteString("connector_name = ")
		builder.WriteString(strconv.Quote(connector.ConnectorName))
		builder.WriteString("\n")
		builder.WriteString("api_key = ")
		builder.WriteString(strconv.Quote(connector.APIKey))
		builder.WriteString("\n")
		if connector.BaseURL != "" {
			builder.WriteString("base_url = ")
			builder.WriteString(strconv.Quote(connector.BaseURL))
			builder.WriteString("\n")
		}
		if connector.SelectedModel != "" {
			builder.WriteString("selected_model = ")
			builder.WriteString(strconv.Quote(connector.SelectedModel))
			builder.WriteString("\n")
		}
		builder.WriteString("display_order = ")
		builder.WriteString(strconv.Itoa(connector.DisplayOrder))
		builder.WriteString("\n")
		if connector.CreatedAt != "" {
			builder.WriteString("created_at = ")
			builder.WriteString(strconv.Quote(connector.CreatedAt))
			builder.WriteString("\n")
		}
		if connector.UpdatedAt != "" {
			builder.WriteString("updated_at = ")
			builder.WriteString(strconv.Quote(connector.UpdatedAt))
			builder.WriteString("\n")
		}
	}

	builder.WriteString("\n")
	builder.WriteString(sectionEnd)
	return builder.String()
}
