package setup

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/HexmosTech/git-lrc/storage"
)

// WriteConfig writes setup results to ~/.lrc.toml.
func WriteConfig(result *SetupResult) error {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to determine home directory: %w", err)
	}

	configPath := filepath.Join(homeDir, ".lrc.toml")

	content := fmt.Sprintf(`# LiveReview CLI configuration
# Generated by: lrc setup
# Date: %s

api_key = %q
api_url = %q
user_email = %q
user_first_name = %q
user_last_name = %q
avatar_url = %q
user_id = %q
org_id = %q
org_name = %q
jwt = %q
refresh_token = %q
`,
		time.Now().Format(time.RFC3339),
		result.PlainAPIKey,
		CloudAPIURL,
		result.Email,
		result.FirstName,
		result.LastName,
		result.AvatarURL,
		result.UserID,
		result.OrgID,
		result.OrgName,
		result.AccessToken,
		result.RefreshToken,
	)

	if err := storage.WriteFileAtomically(configPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	return nil
}

// WriteFileAtomically remains for compatibility and delegates writes to storage.
func WriteFileAtomically(path string, data []byte, mode os.FileMode) error {
	return storage.WriteFileAtomically(path, data, mode)
}
